/*
 * D2JS
 * Copyright (C) SatisKia. All rights reserved.
 */

#ifndef _D2JS_GLGLOBAL_H
#define _D2JS_GLGLOBAL_H

#define _GLPRIMITIVE_TYPE_MODEL		0
#define _GLPRIMITIVE_TYPE_SPRITE	1

#define _GLROTATE_ORDER_XYZ		0
#define _GLROTATE_ORDER_XZY		1
#define _GLROTATE_ORDER_YXZ		2
#define _GLROTATE_ORDER_YZX		3
#define _GLROTATE_ORDER_ZXY		4
#define _GLROTATE_ORDER_ZYX		5

#define _GLSTRIP_TYPE_LINE_STRIP		0
#define _GLSTRIP_TYPE_LINES				1
#define _GLSTRIP_TYPE_TRIANGLE_STRIP	2

#define _GLSHADER_ERROR_COMPILE		0
#define _GLSHADER_ERROR_LINK		1

#endif // _D2JS_GLGLOBAL_H
